#ifndef MODEL_H

#define MODEL_H

/**
 * Calculates a 4x4 model matrix similar to that which would be generated by Blender
 * in XYZ Euler mode, and its inverse.  It may differ slightly from that
 * generated by Blender.
 * @param location_x The X axis of the location of the object in world space.
 *                   Behavior is undefined if NaN, infinity or negative
 *                   infinity.
 * @param location_y The Y axis of the location of the object in world space.
 *                   Behavior is undefined if NaN, infinity or negative
 *                   infinity.
 * @param location_z The Z axis of the location of the object in world space.
 *                   Behavior is undefined if NaN, infinity or negative
 *                   infinity.
 * @param rotation_x The rotation around the X axis, in radians.  Behavior is
 *                   undefined if NaN, infinity or negative infinity.
 * @param rotation_y The rotation around the Y axis, in radians.  Behavior is
 *                   undefined if NaN, infinity or negative infinity.
 * @param rotation_z The rotation around the Z axis, in radians.  Behavior is
 *                   undefined if NaN, infinity or negative infinity.
 * @param scale_x The scale of the object on the X axis, as a multiplying
 *                factor.  Behavior is undefined if NaN, infinity or negative
 *                infinity.
 * @param scale_y The scale of the object on the Y axis, as a multiplying
 *                factor.  Behavior is undefined if NaN, infinity or negative
 *                infinity.
 * @param scale_z The scale of the object on the Z axis, as a multiplying
 *                factor.  Behavior is undefined if NaN, infinity or negative
 *                infinity.
 * @param forward The 4x4 matrix to which to write the result.
 * @param inverse The 4x4 matrix to which to write the inverse of result.
 */
void model(
    const float location_x,
    const float location_y,
    const float location_z,
    const float rotation_x,
    const float rotation_y,
    const float rotation_z,
    const float scale_x,
    const float scale_y,
    const float scale_z,
    float *const forward,
    float *const inverse);

#endif
